FROM node:18.20.3-alpine
RUN corepack enable && corepack prepare pnpm@8.15.4 --activate
WORKDIR /app
COPY package.json pnpm-lock.yaml .npmrc ./
RUN pnpm install
COPY . .

EXPOSE 5173

CMD ["pnpm", "dev"]
