version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: f-inspect-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: ["pnpm", "dev"]

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: f-inspect-prod
    ports:
      - "8080:80"
